#!/usr/bin/env python3
from selenium import webdriver
import selenium
import sys


def init_driver():
    options = webdriver.firefox.options.Options()
    options.headless = True
    return webdriver.Firefox(options=options,
                             executable_path="/bin/geckodriver")


def devlist():
    driver = init_driver()
    driver.get("http://192.168.1.254/cgi-bin/devices.ha")

    dev_table = driver.find_elements_by_xpath(
        "//*[@id=\"content-sub\"]/form/div/table/tbody/*"
    )

    device_enumerator = 0
    for field in dev_table:
        if field.text == "":
            print(f"\n--- Device #{device_enumerator} ---")
            device_enumerator += 1
        else:
            print(field.text)

    driver.quit()


def service():
    service_flags[sys.argv[2]]()


def service_new():
    pass


service_flags = {
    "new": service_new,
}

flags = {
    "devlist": devlist,
    "service": service,
}

if len(sys.argv) > 1:
    flags[sys.argv[1]]()
